Repository inssagram/FE, pull requests merged in 2023-10, with the labels that each got.

#45 markup: direct-page layout
  components/atoms/DirectInHeader.tsx
  components/atoms/DirectPartner.tsx
  components/input/DirectMessage.tsx
  components/input/DirectSearchBar.tsx
  components/list/DmAccountsList.tsx
  components/list/DmContentsList.tsx
  pages/direct/in/index.tsx
  pages/direct/in/styled.tsx
  pages/direct/index.tsx
  pages/direct/new/index.tsx
  pages/direct/new/styled.ts
Labels: 🎨 Html&css

#47 Feat: 마이페이지 레이아웃
  assets/css/spinner.css
  components/Header.tsx
  components/styledHeader.ts
  data.json
  package.json
  pages/main/boardwrite/details/index.tsx
  pages/main/boardwrite/details/styled.ts
  pages/main/boardwrite/index.tsx
  pages/main/boardwrite/story/index.tsx
  pages/main/boardwrite/story/styled.ts
  pages/main/boardwrite/styled.ts
  pages/my/feeds/comments/index.tsx
  pages/my/feeds/comments/styled.ts
  pages/my/feeds/edit/index.tsx
  pages/my/feeds/edit/styled.ts
  pages/my/feeds/index.tsx
  pages/my/feeds/styled.ts
  yarn.lock
Labels: 🎨 Html&css

#49 markup: notifications page layout
  components/atoms/DirectHeader.tsx
  pages/notifications/index.tsx
  pages/notifications/styled.ts
Labels: 🎨 Html&css

#50 feat: reels transition
  components/styledFooter.ts
  pages/reels/index.tsx
  pages/reels/styled.ts
Labels: ✨ Feature, 🎨 Html&css

#53 Main merge
  assets/css/spinner.css
  components/Footer.tsx
  components/Header.tsx
  components/Layout.tsx
  components/atoms/DirectHeader.tsx
  components/atoms/DirectInHeader.tsx
  components/atoms/DirectPartner.tsx
  components/input/DirectMessage.tsx
  components/input/DirectSearchBar.tsx
  components/input/SearchBar.tsx
  components/list/DmAccountsList.tsx
  components/list/DmContentsList.tsx
  components/list/ResultsList.tsx
  components/styledFooter.ts
  components/styledHeader.ts
  data.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/direct/in/index.tsx
  pages/direct/in/styled.tsx
  pages/direct/index.tsx
  pages/direct/new/index.tsx
  pages/direct/new/styled.ts
  pages/direct/styled.ts
  pages/explore/index.tsx
  pages/explore/styled.ts
  pages/index.tsx
  pages/main/boardwrite/details/index.tsx
  pages/main/boardwrite/details/styled.ts
  pages/main/boardwrite/index.tsx
  pages/main/boardwrite/story/index.tsx
  pages/main/boardwrite/story/styled.ts
  pages/main/boardwrite/styled.ts
  pages/main/index.tsx
  pages/main/spinner.scss
  pages/main/styled.ts
  pages/my/feeds/comments/index.tsx
  pages/my/feeds/comments/styled.ts
  pages/my/feeds/edit/index.tsx
  pages/my/feeds/edit/styled.ts
  pages/my/feeds/index.tsx
  pages/my/feeds/styled.ts
  pages/my/index.tsx
  pages/my/styled.ts
  pages/notifications/index.tsx
  pages/notifications/styled.ts
  pages/reels/index.tsx
  pages/reels/styled.ts
  pages/search/index.tsx
  pages/search/styled.ts
  pages/story/index.tsx
  pages/story/styled.ts
  public/fonts/JejuGothic.TTF
  public/images/cat.jpg
  public/images/coffee.jpg
  public/images/profile.jpg
  styles/globals.css
  yarn.lock
Labels: 🌏 Deploy, 📃 Docs

#54 feat: signupPage layout & 중복검사
  db.json
  email.json
  package.json
  pages/signup/auth.tsx
  pages/signup/details.tsx
  pages/signup/index.tsx
  pages/signup/styled.ts
Labels: ✨ Feature, 🎨 Html&css

#55 Feat: 로그인, 로그아웃 페이지 레이아웃
  pages/main/boardwrite/details/index.tsx
  pages/main/boardwrite/story/index.tsx
  pages/my/feeds/comments/index.tsx
  pages/my/feeds/edit/index.tsx
  pages/my/feeds/index.tsx
  pages/my/login/index.tsx
  pages/my/login/styled.ts
  pages/my/logout/index.tsx
  pages/my/logout/styled.ts
  public/images/logo.png
Labels: 🎨 Html&css

#58 feat: signup > auth Page
  email.json
  pages/main/index.tsx
  pages/signup/auth.tsx
  pages/signup/auth/index.tsx
  pages/signup/auth/styled.ts
  pages/signup/details.tsx
  pages/signup/details/index.tsx
  pages/signup/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#59 feat: signup > details Page
  email.json
  pages/signup/details/index.tsx
  pages/signup/details/styled.ts
  pages/story/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#60 Feat: explore page > post page test (with json server)
  components/atoms/DirectInHeader.tsx
  components/atoms/post/PostContent.tsx
  components/atoms/post/styled.ts
  explore.json
  package.json
  pages/direct/in/styled.tsx
  pages/direct/new/styled.ts
  pages/explore/index.tsx
  pages/notifications/index.tsx
  pages/post/[id].tsx
  pages/post/styled.ts
  post.json
  public/images/gopchang.jpg
  public/images/maratang.jpg
  utils/api.js
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#72 Feat: search-page 검색 기능 구현
  components/Footer.tsx
  components/input/SearchBar.tsx
  components/list/ResultsList.tsx
  explore.json
  json-server-data/account.json
  pages/explore/search/index.tsx
  pages/post/[id].tsx
  pages/search/index.tsx
Labels: ✨ Feature

#80 직업 api 연동성공 및 검색기능 구현
  .babelrc
  .env
  .github/workflows/npm-publish-github-packages.yml
  components/backbutton.tsx
  json-server-data/email.json
  next.config.js
  pages/reels/index.tsx
  pages/signup/auth/index.tsx
  pages/signup/details/index.tsx
  pages/signup/index.tsx
  pages/signup/job/index.tsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#83 Feat: direct-new-page 새로운 채팅방 만들기
  components/Footer.tsx
  components/Header.tsx
  components/atoms/DirectHeader.tsx
  components/atoms/DirectInHeader.tsx
  components/atoms/Icons.tsx
  components/atoms/post/PostContent.tsx
  components/atoms/post/styled.ts
  components/input/DirectSearchBar.tsx
  components/list/DmAccountsList.tsx
  components/list/DmSearchList.tsx
  components/list/ResultsList.tsx
  kj.json
  package.json
  pages/direct/index.tsx
  pages/direct/new/index.tsx
  pages/explore/index.tsx
  pages/notifications/index.tsx
  pages/post/[id].tsx
  styled/direct_new.ts
  styled/explore.ts
Labels: ✨ Feature, 🎨 Html&css

#84 Document: _document .tsx / Fix: FOUC
  components/Footer.tsx
  components/Header.tsx
  components/backbutton.tsx
  components/list/DmSearchList.tsx
  components/styled/direct.ts
  components/styled/direct_new.ts
  components/styled/explore.ts
  components/styled/main.ts
  components/styled/main_boardwirte_story.ts
  components/styled/main_boardwrite.ts
  components/styled/main_boardwrite_details.ts
  components/styled/my.ts
  components/styled/my_feeds.ts
  components/styled/my_feeds_comments.ts
  components/styled/my_feeds_edit.ts
  components/styled/my_login.ts
  components/styled/my_logout.ts
  components/styled/my_profile.ts
  components/styled/notifications.ts
  components/styled/post.ts
  components/styled/reels.ts
  components/styled/search.ts
  components/styled/signup.ts
  components/styled/signup_auth.ts
  components/styled/signup_details.ts
  components/styled/signup_job.ts
  components/styled/spinner.scss
  components/styled/story.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/create/details/index.tsx
  pages/create/index.tsx
  pages/create/story/index.tsx
  pages/direct/index.tsx
  pages/direct/new/index.tsx
  pages/explore/index.tsx
  pages/explore/search/index.tsx
  pages/main/index.tsx
  pages/my/feeds/[id].tsx
  pages/my/feeds/comments/index.tsx
  pages/my/feeds/edit/index.tsx
  pages/my/feeds/index.tsx
  pages/my/index.tsx
  pages/my/login/index.tsx
  pages/my/logout/index.tsx
  pages/my/profile/index.tsx
  pages/notifications/index.tsx
  pages/post/[id].tsx
  pages/reels/index.tsx
  pages/signup/auth/index.tsx
  pages/signup/details/index.tsx
  pages/signup/index.tsx
  pages/signup/job/index.tsx
  pages/story/index.tsx
  yarn.lock
Labels: 🐞 BugFix, 📃 Docs

#86 fix
  pages/signup/job/index.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#90 Feat : 내 피드 무한스크롤 기능 구현
  components/Footer.tsx
  components/list/ResultsList.tsx
  components/styled/my.ts
  pages/direct/new/index.tsx
  pages/my/feeds/index.tsx
  pages/my/index.tsx
  pages/my/settings/profile/index.tsx
Labels: ✨ Feature

#91 Feat: direct-page 계정 검색하기, 메세지 보내기 & 받기 테스트
  components/atoms/DirectInHeader.tsx
  components/atoms/DirectPartner.tsx
  components/atoms/Icons.tsx
  components/input/DirectMessage.tsx
  components/input/DirectSearchBar.tsx
  components/list/DmAccountsList.tsx
  components/list/DmContentsList.tsx
  components/list/DmSearchList.tsx
  kj.json
  pages/direct/in/[id].tsx
  pages/direct/in/index.tsx
  pages/direct/index.tsx
  pages/direct/new/index.tsx
  pages/post/[id].tsx
  public/images/jungho.jpg
  public/images/kyungjin.jpg
  public/images/sam.jpg
  public/images/yuri.jpg
Labels: ✨ Feature

#94 feat: 계정 설정 post / patch
  json-server-data/account.json
  json-server-data/email.json
  pages/my/settings/account/index.tsx
  pages/my/settings/job/index.tsx
  pages/signup/details/index.tsx
  pages/signup/job/index.tsx
Labels: 📬 API, 🔨 Refactor

#99 fix: reels 오버스크롤 시 돌아오기
  pages/reels/index.tsx
Labels: 🐞 BugFix

#102 Refactor: MainPage: Story Part
  assets/css/spinner.css
  components/styled/main.ts
  components/styled/spinner.scss
  json-server-data/story.json
  pages/main/index.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#107 Feat: 댓글 등록, 삭제(Redux tollkit 적용)
  components/styled/main_boardwrite_details.ts
  components/styled/modal.ts
  components/styled/my_feeds_comments.ts
  data.json
  package.json
  pages/_app.tsx
  pages/create/details/index.tsx
  pages/create/index.tsx
  pages/main/index.tsx
  pages/my/feeds/[id].tsx
  pages/my/feeds/[id]/comments/index.tsx
  pages/my/feeds/[id]/comments/modal.tsx
  pages/my/feeds/[id]/comments/useLongPress.tsx
  pages/my/feeds/comments/index.tsx
  pages/my/feeds/index.tsx
  src/redux/Posts/commentSlice.ts
  src/redux/Posts/postSlice.ts
  src/redux/Posts/store.ts
  tsconfig.json
  yarn.lock
Labels: ⚙ Setting, ✨ Feature, 🎨 Html&css

#109 feat: story page 컨텐츠 내 사진 이동 컨텐츠 종료 시 메인으로 이동
  assets/css/spinner.css
  components/styled/story.ts
  json-server-data/storypage.json
  next.config.js
  pages/story/index.tsx
Labels: ✨ Feature, 🔨 Refactor

#110 Feat: 검색 페이지 해시태그 검색 기능 구현
  .env
  .gitignore
  components/atoms/Icons.tsx
  components/atoms/PageHeader.tsx
  components/atoms/TagsHeader.tsx
  components/input/SearchBar.tsx
  components/list/ResultsList.tsx
  components/list/SearchList/SearchList.tsx
  components/list/SearchList/styled.ts
  kj.json
  pages/explore/index.tsx
  pages/explore/search/index.tsx
  pages/explore/tags/[name].tsx
  pages/post/[id].tsx
  public/images/hashtag.jpg
  services/api.js
  utils/date.ts
Labels: ⚙ Setting, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#112 feat: onAnimationEnd => toggleFlag => 애니메이션 실행
  components/Layout.tsx
  package.json
  pages/direct/in/[id].tsx
  pages/story/index.tsx
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#113 Fix: direct-page 이미지 업로드 에러
  components/input/DirectMessage/DirectMessage.tsx
  components/list/DmContentsList.tsx
  pages/direct/in/[id].tsx
  utils/fileToDataUrl.ts
Labels: 🐞 BugFix

#115 Feat: 내 프로필 자기소개 변경
  components/styled/my.ts
  data.json
  package.json
  pages/_app.tsx
  pages/my/index.tsx
  pages/my/settings/profile/index.tsx
  src/redux/Posts/store.ts
  src/redux/Posts/userProfileSlice.ts
  yarn.lock
Labels: ✨ Feature

#116 fix: zIndex
  components/Layout.tsx
  pages/story/index.tsx
Labels: 🐞 BugFix

#117 Dev
  components/Layout.tsx
Labels: 🐞 BugFix

#119 fix: 이미지 넘어갈 때 전 이미지 고정하기
  pages/story/index.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#120 Setting: axios instance setting
  components/atoms/PostDetails/PostDetails.tsx
  components/atoms/PostHeader/PostHeader.tsx
  components/atoms/PostHeader/styled.ts
  kj.json
  services/api.js
  services/instance.js
Labels: ⚙ Setting

#123 fix: 서버 주소 환경변수 설정
  .env
  next.config.js
  pages/signin/index.tsx
Labels: ⚙ Setting

#125 Feat: 메인페이지 게시글 api 연동 & 테스트 and Setting: customAxios & api 호출 디렉토리
  .env
  components/Post/Contents.tsx
  components/Post/Top.tsx
  components/atoms/Modal.tsx
  pages/main/index.tsx
  pages/notifications/index.tsx
  public/images/noImage.svg
  public/images/noProfile.jpg
  public/images/noProfile.svg
  services/customAxios.ts
  services/notificationInfo/getNotificationList.ts
  src/redux/Posts/postSlice.ts
  src/redux/Posts/userSlice.ts
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor
