Repository inssagram/FE, pull requests merged in 2023-11, with the labels that each got.

#127 Dev
  .env
  pages/signup/auth/index.tsx
  pages/signup/details/index.tsx
  pages/signup/emailState.ts
  pages/signup/index.tsx
  pages/signup/job/index.tsx
  src/redux/Posts/store.ts
Labels: ✨ Feature

#128 API: my-page 게시글 관련 코드 수정 & api 연동
  components/Post/Top.tsx
  components/atoms/Modal.tsx
  components/styled/my.ts
  components/styled/my_feeds.ts
  pages/main/index.tsx
  pages/main/modal.tsx
  pages/my/feeds/[id].tsx
  pages/my/index.tsx
  services/postInfo/getMyPostAll.ts
  services/postInfo/getPostDetail.ts
  src/redux/Posts/userSlice.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#130 Refactor: userSlice 리덕스 관련 코드 수정
  components/Post/Top.tsx
  pages/main/index.tsx
  pages/main/modal.tsx
  pages/signin/index.tsx
  services/instance.ts
  services/notificationInfo/getNotificationList.ts
  services/postInfo/getPostAll.ts
  services/postInfo/getPostDetail.ts
  src/redux/Posts/userSlice.ts
Labels: 📬 API, 🔨 Refactor

#132 fix: Redux 전역상태 이름 변경 및 버그 수정
  pages/signup/auth/index.tsx
  pages/signup/emailState.ts
  pages/signup/job/index.tsx
Labels: 🐞 BugFix, 📬 API

#134 fix: placeholder font/color
  components/styled/signin.ts
  components/styled/signup_details.ts
  pages/signin/index.tsx
  pages/signup/auth/index.tsx
  pages/signup/details/index.tsx
  pages/signup/job/index.tsx
Labels: 🐞 BugFix

#137 Feat : 게시글 수정, 삭제 구현
  components/Post/Top.tsx
  components/atoms/EditModal.tsx
  components/atoms/Modal.tsx
  pages/my/feeds/[id].tsx
  pages/my/feeds/[id]/comments/modal.tsx
  pages/my/feeds/edit/index.tsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#145 fix: 이메일 확인 요청 시 오버클릭 방지
  .env
  components/firebase/firebase.ts
  components/styled/main_boardwirte_story.ts
  components/styled/story.ts
  next.config.js
  package.json
  pages/create/story/index.tsx
  pages/signup/details/index.tsx
  pages/signup/index.tsx
  pages/signup/job/index.tsx
  yarn.lock
Labels: 🐞 BugFix

#148 fix: signup error
  pages/create/story/index.tsx
  pages/signup/emailState.ts
  pages/signup/job/index.tsx
Labels: 🐞 BugFix

#152 API: 게시글 페이지 & 댓글 페이지 request, response 연결 및 기능 테스트
  components/Footer.tsx
  components/Header.tsx
  components/Post/Contents.tsx
  components/Post/Top.tsx
  components/atoms/Button.tsx
  components/atoms/Header.tsx
  components/atoms/Item.tsx
  components/styled/my.ts
  components/styled/signin.ts
  pages/index.tsx
  pages/my/feeds/[id]/comments/index.tsx
  pages/my/index.tsx
  pages/notifications/index.tsx
  pages/post/[id].tsx
  pages/post/comment/liked_by/[commentId].tsx
  pages/post/liked_by/[postId].tsx
  pages/user/[id].tsx
  services/postInfo/getLikeCommentMemberList.ts
  services/postInfo/getLikePostMemberList.ts
  yarn.lock
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor

#153 feat: firebase upload iamge
  .env
  components/firebase/firebase.ts
  components/styled/main_boardwirte_story.ts
  next.config.js
  package.json
  pages/create/story/index.tsx
  pages/signup/job/index.tsx
  yarn.lock
Labels: 🐞 BugFix, 📬 API

#155 refactor: create/details 이미지 업로드 및 파이어베이스연동
  components/Header.tsx
  components/styled/main_boardwrite_details.ts
  pages/create/details/index.tsx
  pages/create/story/index.tsx
  pages/signup/job/index.tsx
Labels: 🔨 Refactor

#156 "fix: JOBLIST_API_KEY 누락" "refactor: 회원가입 페이지 변경"
  components/firebase/firebase.ts
  next.config.js
  pages/signup/details/index.tsx
  pages/signup/index.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#157 reafactor: firebase auth 로직 삭제, Post 생성 후 생성된 게시글로 이동
  components/firebase/firebase.ts
  pages/create/details/index.tsx
  pages/signup/job/index.tsx
Labels: 🔨 Refactor

#158 fix: 마이페이지 네비게이션바 오류 해결, 검색페이지 & 알림페이지 api 연동 오류 재확인
  components/Chat/AccountList.tsx
  components/Post/Contents.tsx
  components/atoms/Button.tsx
  components/atoms/Item.tsx
  components/atoms/Modal.tsx
  components/input/SearchBar.tsx
  components/styled/my.ts
  components/styled/notifications.ts
  pages/direct/new/index.tsx
  pages/my/index.tsx
  pages/notifications/index.tsx
  pages/post/comment/liked_by/[commentId].tsx
  pages/post/liked_by/[postId].tsx
  pages/user/[id].tsx
  services/chatInfo/postChatRoom.ts
Labels: 🐞 BugFix, 📬 API

#159 API: 채팅페이지 api 연동
  components/Chat/AccountList.tsx
  components/Chat/ChatList.tsx
  components/Chat/ChatRoomList.tsx
  components/Chat/MemberProfile.tsx
  components/Chat/SearchInput.tsx
  components/Header.tsx
  components/atoms/DirectPartner.tsx
  components/atoms/Header.tsx
  components/styled/header.ts
  pages/direct/in/[roomId].tsx
  pages/direct/index.tsx
  pages/direct/new/index.tsx
  services/chatInfo/getChatRoom.ts
  services/chatInfo/getChatRoomList.ts
Labels: 📬 API

#162 Fix: searchBar 렌더링 오류 수정
  components/Chat/AccountList.tsx
  components/Chat/SearchInput.tsx
  components/atoms/SearchBar.tsx
  pages/direct/new/index.tsx
  pages/explore/index.tsx
  pages/explore/search/index.tsx
Labels: 🐞 BugFix

#163 fix: image 파일명 업로드
  pages/create/details/[id].tsx
  pages/create/details/index.tsx
Labels: 🔨 Refactor

#164 feat: add resizer func
  package.json
  pages/create/details/handleResizeImage.ts
  pages/create/details/index.tsx
  pages/create/story/index.tsx
  yarn.lock
Labels: ✨ Feature

#168 API: 알림페이지 삭제하기 버튼에 기능 추가 & API 연동
  components/Footer.tsx
  components/Header.tsx
  components/atoms/Button.tsx
  components/atoms/Item.tsx
  components/atoms/Modal.tsx
  components/styled/atoms_modal.ts
  components/styled/notifications.ts
  pages/my/feeds/[id]/comments/index.tsx
  pages/my/feeds/[id]/comments/modal.tsx
  pages/notifications/index.tsx
  services/notificationInfo/deleteNotificationAll.ts
  types/NotificationTypes.ts
Labels: 🐞 BugFix, 📬 API

#170 fix: job 요청 보내기
  pages/signup/job/index.tsx
Labels: 🐞 BugFix

#171 refactor: story 이미지 리사이징 & 리팩토링
  components/Header.tsx
  components/styled/header.ts
  components/styled/signin.ts
  pages/create/details/handleResizeImage.ts
  pages/create/story/index.tsx
  pages/signup/job/index.tsx
  pages/story/getStorydata.ts
  pages/story/index.tsx
Labels: 🔨 Refactor

#178 API: 채팅페이지 기능 구현 & api 연동, 게시글 공유하기
  components/Chat/AccountList.tsx
  components/Chat/ChatRoom.tsx
  components/Chat/ChatRoomList.tsx
  components/Chat/Header.tsx
  components/Chat/MemberProfile.tsx
  components/Chat/MessageInput.tsx
  components/Chat/SearchInput.tsx
  components/Chat/SharedPost.tsx
  components/Footer.tsx
  components/Header.tsx
  components/Post/Contents.tsx
  components/atoms/Button.tsx
  components/atoms/Header.tsx
  components/atoms/Item.tsx
  components/atoms/Modal.tsx
  components/styled/my.ts
  pages/direct/in/[roomId].tsx
  pages/direct/index.tsx
  pages/direct/new/index.tsx
  pages/explore/search/index.tsx
  pages/main/index.tsx
  pages/my/feeds/[id]/comments/index.tsx
  pages/my/feeds/[id]/comments/useLongPress.tsx
  pages/my/index.tsx
  pages/post/[id].tsx
  pages/post/comment/liked_by/[commentId].tsx
  pages/post/liked_by/[postId].tsx
  pages/post/share/[id].tsx
  pages/user/[memberId].tsx
  services/chatInfo/getChatHistoryWithMemberId.ts
  services/chatInfo/getChatHistoryWithRoomId.ts
  services/chatInfo/postNewMessage.ts
  services/chatInfo/postSharePost.ts
  services/chatInfo/webSocketHandler.tsx
  services/postInfo/getFollowingMemberPostAll.ts
  types/ChatRoomTypes.ts
  types/PostTypes.ts
  types/SearchItemTypes.ts
  types/UserTypes.ts
Labels: 📬 API, 🔨 Refactor

#191 delete 불필요한 파일 삭제
  components/Post/Contents.tsx
  components/styled/my.ts
  constant/union.ts
  pages/explore/index.tsx
  pages/explore/post/[id].tsx
  pages/my/[id]/comments/index.tsx
  pages/my/[id]/comments/modal.tsx
  pages/my/[id]/comments/useLongPress.tsx
  pages/my/feeds/[id]/comments/index.tsx
  pages/my/feeds/[id]/comments/modal.tsx
  pages/my/index.tsx
  pages/post/[id].tsx
  types/PostTypes.ts
Labels: 🔨 Refactor

#193 feat: Images Modal & Add Images & Delete Images
  components/styled/create_details.ts
  pages/create/details/index.tsx
  pages/signin/index.tsx
Labels: ✨ Feature

#195 Feat: Drag & Drop
  components/styled/create_details.ts
  pages/create/details/index.tsx
Labels: ✨ Feature

#196 refactor: 다중 이미지 업로드 및 미리보기 구현
  pages/create/details/index.tsx
  pages/signin/index.tsx
Labels: 🔨 Refactor

#202 fix: 게시글 수정하기 handlePostUpdate 함수 타입 오류
  components/Post/Top.tsx
  components/atoms/Modal.tsx
  pages/explore/post/[id].tsx
  pages/my/index.tsx
  pages/post/[id].tsx
  pages/user/[id].tsx
Labels: 🐞 BugFix

#209 Fix: CommentItem 타입 에러 수정
  components/atoms/Comment.tsx
Labels: 🐞 BugFix
