Repository inssagram/FE, pull requests merged in 2023-09, with the labels that each got.

#3 setting: 디렉토리 구조 세팅
  app/favicon.ico
  app/layout.tsx
  app/page.module.css
  app/page.tsx
  components/Footer.tsx
  components/Header.tsx
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/next.svg
  public/vercel.svg
  styles/globals.css
  styles/main.css
  yarn.lock
Labels: ⚙ Setting

#6 Layout
  pages/index.tsx
  pull_request_template.md
Labels: 🎨 Html&css

#8 markup: mainpage
  next.config.js
  package.json
  pages/main.tsx
  styles/globals.css
  styles/main.ts
  yarn.lock
Labels: 🎨 Html&css

#12 feat: story page
  pages/main.tsx
  pages/story.tsx
  styles/main.ts
  styles/story.ts
Labels: 🎨 Html&css

#20 markup: explore page layout
  components/input/SearchBar.tsx
  package.json
  pages/_app.tsx
  pages/explore/index.tsx
  pages/explore/styled.ts
  pages/index.tsx
  public/images/coffee.jpg
  styles/globals.css
  yarn.lock
Labels: 🎨 Html&css

#22 add: Layout components
  components/Layout.tsx
  components/input/SearchBar.tsx
  components/list/ResultsList.tsx
  pages/_app.tsx
  pages/search/index.tsx
  pages/search/styled.ts
  public/images/profile.jpg
Labels: 🎨 Html&css

#28 markup: 폰트 설정 & 검색, 탐색 페이지 css 변경
  components/input/SearchBar.tsx
  components/result/ResultsList.tsx
  pages/_app.tsx
  pages/explore/index.tsx
  pages/explore/styled.ts
  pages/main/index.tsx
  pages/search/index.tsx
  pages/search/styled.ts
  public/fonts/JejuGothic.TTF
  styles/globals.css
Labels: 🎨 Html&css

#32 Layout
  pages/main/index.tsx
  pages/reels/index.tsx
  pages/reels/styled.ts
  pages/story/index.tsx
  pages/story/styled.ts
Labels: 🎨 Html&css

#33 fix: fontsize
  pages/story/styled.ts
Labels: 🐞 BugFix

#34 markup: direct page layout
  components/atoms/DirectHeader.tsx
  components/list/DirectList.tsx
  components/list/ResultsList.tsx
  pages/direct/index.tsx
  pages/direct/styled.ts
  pages/search/index.tsx
Labels: 🎨 Html&css

#35 feat: story button animation
  package.json
  pages/_app.tsx
  pages/main/index.tsx
  pages/main/spinner.scss
  pages/main/styled.ts
  yarn.lock
Labels: ⚙ Setting, ✨ Feature, 🎨 Html&css

#37 feat: story page flip
  pages/main/index.tsx
  pages/reels/index.tsx
  pages/story/index.tsx
  pages/story/styled.ts
  styles/globals.css
Labels: ✨ Feature, 🎨 Html&css
